root = "."
tmp_dir = "tmp"

[build]
# Просто команда для сборки. Вы можете использовать `make` или другие инструменты
cmd = "go build -race -o ./tmp/scraper ./cmd/..."
# Бинарный файл, полученный в результате сборки
bin = "tmp/scraper"
# Пользовательские команды для выполнения при запуске
full_bin = "APP_ENV=dev APP_USER=air ./tmp/scraper"
# Следить за этими расширениями файлов
include_ext = ["go", "tpl", "tmpl", "html"]
# Игнорировать эти расширения файлов или каталоги
exclude_dir = ["assets", "tmp", "vendor", "testdata", "td", ".tdlib"]
# Следить за этими каталогами, если указано
include_dir = []
# Игнорировать эти файлы
exclude_file = []
# Это log файл
log = "air_errors.log"
# Это время ожидания после каждой сборки
delay = 1000 # ms
# Остановить запущенный бинарный файл перед сборкой
stop_on_error = true
# Отправлять Interrupt перед завершением процесса (не работает в Windows)
send_interrupt = true
# Задержка отправки interrupt сигнала
kill_delay = 5000 # ms

[log]
# Показывать время в логах
time = true

[color]
# Пользовательские цвета для каждого типа логов
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Удалять временные файлы при выходе
clean_on_exit = true
