// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns status ok",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/scrape": {
            "get": {
                "description": "Handle scrape request with query parameters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scrape"
                ],
                "summary": "Scrape request",
                "parameters": [
                    {
                        "type": "string",
                        "default": "https://t.me/addlist/4eTLcGIrIx9hNzUy",
                        "description": "Chat folder link",
                        "name": "chat_folder_link",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "default": "2025-05-20T15:02:00+04:00",
                        "description": "Right bound datetime",
                        "name": "right_bound",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "default": "2025-05-19T15:02:00+04:00",
                        "description": "Left bound datetime",
                        "name": "left_bound",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Social flag",
                        "name": "social",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
